# version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    # env_file:
    #   - ./mongo.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./server.env
    depends_on:
      - mongodb
    volumes:
      - images:/usr/src/app/images

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3000:3000"
    # stdin_open: true
    # tty: true
    depends_on:
      - server

  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    depends_on:
      - client

volumes:
  data:
  images:
