# version: "3.8"
# in production mode nextjs must be built and its env variable have to
# be receive in dockerfile build stage so env file (.env) must
# be defined in client directory

services:
  mongodb:
    image: "mongo:7"
    volumes:
      - data:/data/db
    # env_file:
    #   - ./mongo.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./server.env
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: prod
    # stdin_open: true
    # tty: true
    depends_on:
      - server

  nginx:
    image: "nginx:1"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
    environment:
      - NGINX_PORT=80
    depends_on:
      - client

volumes:
  data:
