# version: "3.8"

services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    # env_file:
    #   - ./mongo.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      # - /app/dist
    env_file:
      - ./server.env
    depends_on:
      - mongodb


      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./client.env
    # stdin_open: true
    # tty: true
    # depends_on:
    #   - server

  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    depends_on:
      - client

volumes:
  data:
