# version: "3.8"
# in production mode nextjs must be built and its env variable have to
# be receive in dockerfile build stage so env file (.env) must
# be defined in client directory so it doesn't need any other env file
# because we use this .env file for passing env variables

services:
  mongodb:
    image: "mongo:7"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    # env_file:
    #   - ./mongo.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./server:/app
      - /app/node_modules
      # - /app/dist
    env_file:
      - ./server.env
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    # stdin_open: true
    # tty: true
    depends_on:
      - server

  nginx:
    image: "nginx:1"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.development.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    depends_on:
      - client

volumes:
  data:
